# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-22 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=45)),
                ('date', models.DateTimeField(default=None)),
                ('time', models.DateTimeField(default=None)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='myApp.User')),
            ],
        ),
    ]
